print("¿COMO LAVAR LOS PLATOS")
print("1. Preparación:")
print("- Retirar los restos de comida de los platos con una espátula o servilleta.")
print("- Despejar el fregadero de cualquier objeto y asegurarte de que esté limpio")
print("2. Lavar: ")
print("- Llenar el fregadero con agua caliente y jabón para lavavajillas.")
print("- Sumergir los platos en el agua jabonosa.")
print("- Fregar los platos con una esponja o paño, comenzando por los menos sucios y terminando por los más sucios.")
print("- Para platos con comida adherida, se puede usar una escobilla o cepillo de cocina.")
print("3. Enjuagar:")
print("- Enjuagar los platos con agua caliente, asegurándose de eliminar todo el jabón.")
print("- Para platos con grasa, se puede usar un paño limpio para secar y evitar la formación de manchas.")
print("4. Secar:")
print("- Colocar los platos limpios sobre un escurridor o toalla para que se sequen al aire.")
print("- Para vasos y copas, se puede usar un paño limpio para secarlos y evitar manchas.")