print("DIALOGO ENTRE UN DUEÑO Y SU GATO")
print("Gato: Miau")
print("Dueño: Aquí estoy, minino. Te acariciaré enseguida")
print("Gato: Miau miau")
print("Dueño: Lo siento, peludito. Te consentiré ahora mismo.")
print("Gato: Miau miau")